In [1]:
# Project Milestone 3
## Cleaning / Formatting Website Data
## Justin Wisniewski

In [2]:
# Importing the required libraries
import requests
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
from bs4 import BeautifulSoup

In [3]:
# Downloading contents of the web page
url = "https://www.nflpenalties.com"
data = requests.get(url).text

In [4]:
# Creating BeautifulSoup object
soup = BeautifulSoup(data, 'html.parser')

In [5]:
# Verifying tables and their classes
print('Classes of each table:')
for table in soup.find_all('table'):
    print(table.get('class'))

Classes of each table:
['footable']

In [6]:
data_table = soup.find("table",{"class":"footable"})
print(type(data_table))

<class 'bs4.element.Tag'>

In [7]:
df=pd.read_html(str(data_table))
# Convert list to dataframe
df=pd.DataFrame(df[0])
print(df.head())

          Team  Games  Plays  Against Count  Against Yards  Beneficiary Count  \
0      LA Rams      6    865             24            205                 28
1      Buffalo      6    899             36            230                 37
2      Atlanta      7   1040             30            231                 40
3  New Orleans      7   1115             52            459                 44
4     Carolina      7   1042             34            328                 51

   Beneficiary Yards  Net Count  Net Yards  Pre-snap Count  Declined  \
0                211        4.0        6.0              11         3
1                319        1.0       89.0              16         7
2                350       10.0      119.0              13         7
3                366       -8.0      -93.0              19         6
4                381       17.0       53.0              10         7

   Offsetting  Total Flags  Home  Away
0           1           28    17     7
1           2           45    13    23
2           1           38    14    16
3           2           60    29    23
4           2           43    26     8

In [8]:
# Iterating the columns
for col in df.columns:
    print(col)

Team
Games
Plays
Against Count
Against Yards
Beneficiary Count
Beneficiary Yards
Net Count
Net Yards
Pre-snap Count
Declined
Offsetting
Total Flags
Home
Away

In [9]:
# Step 1
# Replace Headers
# Home will be renamed to Flags at Home Game, Away will be renamed to Flags at Away Game
df = df.rename(columns={'Home': 'Flags at Home Game', 'Away': 'Flags at Away Game'})

In [10]:
df

,Team,Games,Plays,Against Count,Against Yards,Beneficiary Count,Beneficiary Yards,Net Count,Net Yards,Pre-snap Count,Declined,Offsetting,Total Flags,Flags at Home Game,Flags at Away Game
0,LA Rams,6,865,24,205,28,211,4.0,6.0,11,3,1,28,17,7
1,Buffalo,6,899,36,230,37,319,1.0,89.0,16,7,2,45,13,23
2,Atlanta,7,1040,30,231,40,350,10.0,119.0,13,7,1,38,14,16
3,New Orleans,7,1115,52,459,44,366,-8.0,-93.0,19,6,2,60,29,23
4,Carolina,7,1042,34,328,51,381,17.0,53.0,10,7,2,43,26,8
5,Cleveland,7,1097,45,357,41,355,-4.0,-2.0,14,3,2,50,23,22
6,San Francisco,7,1037,48,350,37,322,-11.0,-28.0,20,6,3,57,15,33
7,Chicago,6,866,31,253,39,310,8.0,57.0,13,6,1,38,13,18
8,Cincinnati,7,1096,34,233,36,304,2.0,71.0,15,6,1,41,15,19
9,Pittsburgh,6,954,37,258,34,240,-3.0,-18.0,12,7,2,46,18,19
10,Detroit,6,950,38,329,39,270,1.0,-59.0,11,7,2,47,16,22
11,Philadelphia,6,955,31,233,32,263,1.0,30.0,9,2,4,37,13,18
12,Indianapolis,7,1099,42,347,34,252,-8.0,-95.0,11,5,1,48,18,24
13,Houston,6,937,33,265,43,374,10.0,109.0,16,7,2,42,15,18
14,New England,6,896,38,299,27,235,-11.0,-64.0,17,4,1,43,9,29
15,Miami,6,890,43,331,24,271,-19.0,-60.0,12,8,1,52,18,25
16,N.Y. Jets,7,1096,48,526,45,330,-3.0,-196.0,11,6,0,54,15,33
17,Baltimore,7,1050,36,289,34,269,-2.0,-20.0,13,6,0,42,19,17
18,Washington,7,1093,46,425,44,347,-2.0,-78.0,14,6,1,53,26,20
19,Jacksonville,7,1071,45,330,40,311,-5.0,-19.0,18,2,3,50,22,23
20,Arizona,7,1111,42,368,42,327,0.0,-41.0,15,7,0,49,17,25
21,Kansas City,7,1109,37,370,45,362,8.0,-8.0,9,6,4,47,16,21
22,Las Vegas,6,909,39,291,39,362,0.0,71.0,14,6,1,46,19,20
23,LA Chargers,7,1106,41,337,43,426,2.0,89.0,15,7,3,51,28,13
24,Minnesota,6,923,25,185,43,368,18.0,183.0,10,3,0,28,13,12
25,Green Bay,7,1030,40,288,43,381,3.0,93.0,12,6,0,46,21,19
26,N.Y. Giants,7,1061,48,374,55,415,7.0,41.0,13,8,1,57,26,22
27,Tennessee,6,869,39,346,42,287,3.0,-59.0,12,6,2,47,16,23
28,Tampa Bay,7,1086,40,323,47,345,7.0,22.0,21,3,1,44,17,23
29,Dallas,7,1064,49,377,44,347,-5.0,-30.0,21,7,2,58,26,23
30,Seattle,7,1069,57,503,42,386,-15.0,-117.0,19,6,2,65,17,40
31,Denver,7,1089,58,520,52,474,-6.0,-46.0,25,6,0,64,29,29
32,Totals,106,16237,1286,10560,1286,10560,NaN,NaN,461,182,48,1516,599,687

In [11]:
# Step 2
# Sort rows into more readable format, we are concerned about net yards
# Below we see the NY Jets from a yardage standpoint have the most net yards of penalties called against them
# Minnesota Vikings are most favored
df.sort_values(by=['Net Yards'])

,Team,Games,Plays,Against Count,Against Yards,Beneficiary Count,Beneficiary Yards,Net Count,Net Yards,Pre-snap Count,Declined,Offsetting,Total Flags,Flags at Home Game,Flags at Away Game
16,N.Y. Jets,7,1096,48,526,45,330,-3.0,-196.0,11,6,0,54,15,33
30,Seattle,7,1069,57,503,42,386,-15.0,-117.0,19,6,2,65,17,40
12,Indianapolis,7,1099,42,347,34,252,-8.0,-95.0,11,5,1,48,18,24
3,New Orleans,7,1115,52,459,44,366,-8.0,-93.0,19,6,2,60,29,23
18,Washington,7,1093,46,425,44,347,-2.0,-78.0,14,6,1,53,26,20
14,New England,6,896,38,299,27,235,-11.0,-64.0,17,4,1,43,9,29
15,Miami,6,890,43,331,24,271,-19.0,-60.0,12,8,1,52,18,25
27,Tennessee,6,869,39,346,42,287,3.0,-59.0,12,6,2,47,16,23
10,Detroit,6,950,38,329,39,270,1.0,-59.0,11,7,2,47,16,22
31,Denver,7,1089,58,520,52,474,-6.0,-46.0,25,6,0,64,29,29
20,Arizona,7,1111,42,368,42,327,0.0,-41.0,15,7,0,49,17,25
29,Dallas,7,1064,49,377,44,347,-5.0,-30.0,21,7,2,58,26,23
6,San Francisco,7,1037,48,350,37,322,-11.0,-28.0,20,6,3,57,15,33
17,Baltimore,7,1050,36,289,34,269,-2.0,-20.0,13,6,0,42,19,17
19,Jacksonville,7,1071,45,330,40,311,-5.0,-19.0,18,2,3,50,22,23
9,Pittsburgh,6,954,37,258,34,240,-3.0,-18.0,12,7,2,46,18,19
21,Kansas City,7,1109,37,370,45,362,8.0,-8.0,9,6,4,47,16,21
5,Cleveland,7,1097,45,357,41,355,-4.0,-2.0,14,3,2,50,23,22
0,LA Rams,6,865,24,205,28,211,4.0,6.0,11,3,1,28,17,7
28,Tampa Bay,7,1086,40,323,47,345,7.0,22.0,21,3,1,44,17,23
11,Philadelphia,6,955,31,233,32,263,1.0,30.0,9,2,4,37,13,18
26,N.Y. Giants,7,1061,48,374,55,415,7.0,41.0,13,8,1,57,26,22
4,Carolina,7,1042,34,328,51,381,17.0,53.0,10,7,2,43,26,8
7,Chicago,6,866,31,253,39,310,8.0,57.0,13,6,1,38,13,18
22,Las Vegas,6,909,39,291,39,362,0.0,71.0,14,6,1,46,19,20
8,Cincinnati,7,1096,34,233,36,304,2.0,71.0,15,6,1,41,15,19
23,LA Chargers,7,1106,41,337,43,426,2.0,89.0,15,7,3,51,28,13
1,Buffalo,6,899,36,230,37,319,1.0,89.0,16,7,2,45,13,23
25,Green Bay,7,1030,40,288,43,381,3.0,93.0,12,6,0,46,21,19
13,Houston,6,937,33,265,43,374,10.0,109.0,16,7,2,42,15,18
2,Atlanta,7,1040,30,231,40,350,10.0,119.0,13,7,1,38,14,16
24,Minnesota,6,923,25,185,43,368,18.0,183.0,10,3,0,28,13,12
32,Totals,106,16237,1286,10560,1286,10560,NaN,NaN,461,182,48,1516,599,687

In [13]:
# Step 3
# Add column for Net Yards Per Game
df['Net Yards Per Game'] = df['Net Yards'] / df['Games']

df.head()

,Team,Games,Plays,Against Count,Against Yards,Beneficiary Count,Beneficiary Yards,Net Count,Net Yards,Pre-snap Count,Declined,Offsetting,Total Flags,Flags at Home Game,Flags at Away Game,Net Yards Per Game
0,LA Rams,6,865,24,205,28,211,4.0,6.0,11,3,1,28,17,7,1.000000
1,Buffalo,6,899,36,230,37,319,1.0,89.0,16,7,2,45,13,23,14.833333
2,Atlanta,7,1040,30,231,40,350,10.0,119.0,13,7,1,38,14,16,17.000000
3,New Orleans,7,1115,52,459,44,366,-8.0,-93.0,19,6,2,60,29,23,-13.285714
4,Carolina,7,1042,34,328,51,381,17.0,53.0,10,7,2,43,26,8,7.571429

In [14]:
df.sort_values(by=['Net Yards Per Game'])

,Team,Games,Plays,Against Count,Against Yards,Beneficiary Count,Beneficiary Yards,Net Count,Net Yards,Pre-snap Count,Declined,Offsetting,Total Flags,Flags at Home Game,Flags at Away Game,Net Yards Per Game
16,N.Y. Jets,7,1096,48,526,45,330,-3.0,-196.0,11,6,0,54,15,33,-28.000000
30,Seattle,7,1069,57,503,42,386,-15.0,-117.0,19,6,2,65,17,40,-16.714286
12,Indianapolis,7,1099,42,347,34,252,-8.0,-95.0,11,5,1,48,18,24,-13.571429
3,New Orleans,7,1115,52,459,44,366,-8.0,-93.0,19,6,2,60,29,23,-13.285714
18,Washington,7,1093,46,425,44,347,-2.0,-78.0,14,6,1,53,26,20,-11.142857
14,New England,6,896,38,299,27,235,-11.0,-64.0,17,4,1,43,9,29,-10.666667
15,Miami,6,890,43,331,24,271,-19.0,-60.0,12,8,1,52,18,25,-10.000000
27,Tennessee,6,869,39,346,42,287,3.0,-59.0,12,6,2,47,16,23,-9.833333
10,Detroit,6,950,38,329,39,270,1.0,-59.0,11,7,2,47,16,22,-9.833333
31,Denver,7,1089,58,520,52,474,-6.0,-46.0,25,6,0,64,29,29,-6.571429
20,Arizona,7,1111,42,368,42,327,0.0,-41.0,15,7,0,49,17,25,-5.857143
29,Dallas,7,1064,49,377,44,347,-5.0,-30.0,21,7,2,58,26,23,-4.285714
6,San Francisco,7,1037,48,350,37,322,-11.0,-28.0,20,6,3,57,15,33,-4.000000
9,Pittsburgh,6,954,37,258,34,240,-3.0,-18.0,12,7,2,46,18,19,-3.000000
17,Baltimore,7,1050,36,289,34,269,-2.0,-20.0,13,6,0,42,19,17,-2.857143
19,Jacksonville,7,1071,45,330,40,311,-5.0,-19.0,18,2,3,50,22,23,-2.714286
21,Kansas City,7,1109,37,370,45,362,8.0,-8.0,9,6,4,47,16,21,-1.142857
5,Cleveland,7,1097,45,357,41,355,-4.0,-2.0,14,3,2,50,23,22,-0.285714
0,LA Rams,6,865,24,205,28,211,4.0,6.0,11,3,1,28,17,7,1.000000
28,Tampa Bay,7,1086,40,323,47,345,7.0,22.0,21,3,1,44,17,23,3.142857
11,Philadelphia,6,955,31,233,32,263,1.0,30.0,9,2,4,37,13,18,5.000000
26,N.Y. Giants,7,1061,48,374,55,415,7.0,41.0,13,8,1,57,26,22,5.857143
4,Carolina,7,1042,34,328,51,381,17.0,53.0,10,7,2,43,26,8,7.571429
7,Chicago,6,866,31,253,39,310,8.0,57.0,13,6,1,38,13,18,9.500000
8,Cincinnati,7,1096,34,233,36,304,2.0,71.0,15,6,1,41,15,19,10.142857
22,Las Vegas,6,909,39,291,39,362,0.0,71.0,14,6,1,46,19,20,11.833333
23,LA Chargers,7,1106,41,337,43,426,2.0,89.0,15,7,3,51,28,13,12.714286
25,Green Bay,7,1030,40,288,43,381,3.0,93.0,12,6,0,46,21,19,13.285714
1,Buffalo,6,899,36,230,37,319,1.0,89.0,16,7,2,45,13,23,14.833333
2,Atlanta,7,1040,30,231,40,350,10.0,119.0,13,7,1,38,14,16,17.000000
13,Houston,6,937,33,265,43,374,10.0,109.0,16,7,2,42,15,18,18.166667
24,Minnesota,6,923,25,185,43,368,18.0,183.0,10,3,0,28,13,12,30.500000
32,Totals,106,16237,1286,10560,1286,10560,NaN,NaN,461,182,48,1516,599,687,NaN

In [15]:
# Step 4
# Grouping with functions
df.groupby(["Team","Net Yards Per Game"]).first()

,,Games,Plays,Against Count,Against Yards,Beneficiary Count,Beneficiary Yards,Net Count,Net Yards,Pre-snap Count,Declined,Offsetting,Total Flags,Flags at Home Game,Flags at Away Game
Team,Net Yards Per Game,,,,,,,,,,,,,,
Arizona,-5.857143,7,1111,42,368,42,327,0.0,-41.0,15,7,0,49,17,25
Atlanta,17.000000,7,1040,30,231,40,350,10.0,119.0,13,7,1,38,14,16
Baltimore,-2.857143,7,1050,36,289,34,269,-2.0,-20.0,13,6,0,42,19,17
Buffalo,14.833333,6,899,36,230,37,319,1.0,89.0,16,7,2,45,13,23
Carolina,7.571429,7,1042,34,328,51,381,17.0,53.0,10,7,2,43,26,8
Chicago,9.500000,6,866,31,253,39,310,8.0,57.0,13,6,1,38,13,18
Cincinnati,10.142857,7,1096,34,233,36,304,2.0,71.0,15,6,1,41,15,19
Cleveland,-0.285714,7,1097,45,357,41,355,-4.0,-2.0,14,3,2,50,23,22
Dallas,-4.285714,7,1064,49,377,44,347,-5.0,-30.0,21,7,2,58,26,23
Denver,-6.571429,7,1089,58,520,52,474,-6.0,-46.0,25,6,0,64,29,29
Detroit,-9.833333,6,950,38,329,39,270,1.0,-59.0,11,7,2,47,16,22
Green Bay,13.285714,7,1030,40,288,43,381,3.0,93.0,12,6,0,46,21,19
Houston,18.166667,6,937,33,265,43,374,10.0,109.0,16,7,2,42,15,18
Indianapolis,-13.571429,7,1099,42,347,34,252,-8.0,-95.0,11,5,1,48,18,24
Jacksonville,-2.714286,7,1071,45,330,40,311,-5.0,-19.0,18,2,3,50,22,23
Kansas City,-1.142857,7,1109,37,370,45,362,8.0,-8.0,9,6,4,47,16,21
LA Chargers,12.714286,7,1106,41,337,43,426,2.0,89.0,15,7,3,51,28,13
LA Rams,1.000000,6,865,24,205,28,211,4.0,6.0,11,3,1,28,17,7
Las Vegas,11.833333,6,909,39,291,39,362,0.0,71.0,14,6,1,46,19,20
Miami,-10.000000,6,890,43,331,24,271,-19.0,-60.0,12,8,1,52,18,25
Minnesota,30.500000,6,923,25,185,43,368,18.0,183.0,10,3,0,28,13,12
N.Y. Giants,5.857143,7,1061,48,374,55,415,7.0,41.0,13,8,1,57,26,22
N.Y. Jets,-28.000000,7,1096,48,526,45,330,-3.0,-196.0,11,6,0,54,15,33
New England,-10.666667,6,896,38,299,27,235,-11.0,-64.0,17,4,1,43,9,29
New Orleans,-13.285714,7,1115,52,459,44,366,-8.0,-93.0,19,6,2,60,29,23
Philadelphia,5.000000,6,955,31,233,32,263,1.0,30.0,9,2,4,37,13,18
Pittsburgh,-3.000000,6,954,37,258,34,240,-3.0,-18.0,12,7,2,46,18,19
San Francisco,-4.000000,7,1037,48,350,37,322,-11.0,-28.0,20,6,3,57,15,33
Seattle,-16.714286,7,1069,57,503,42,386,-15.0,-117.0,19,6,2,65,17,40
Tampa Bay,3.142857,7,1086,40,323,47,345,7.0,22.0,21,3,1,44,17,23
Tennessee,-9.833333,6,869,39,346,42,287,3.0,-59.0,12,6,2,47,16,23
Washington,-11.142857,7,1093,46,425,44,347,-2.0,-78.0,14,6,1,53,26,20

In [19]:
# Step 5
# Create new df with team and net yards per game
# Final milestone will have home/away
penalty_df = df[['Team','Net Yards Per Game']].copy()

In [20]:
penalty_df

             Team  Net Yards Per Game
0         LA Rams            1.000000
1         Buffalo           14.833333
2         Atlanta           17.000000
3     New Orleans          -13.285714
4        Carolina            7.571429
5       Cleveland           -0.285714
6   San Francisco           -4.000000
7         Chicago            9.500000
8      Cincinnati           10.142857
9      Pittsburgh           -3.000000
10        Detroit           -9.833333
11   Philadelphia            5.000000
12   Indianapolis          -13.571429
13        Houston           18.166667
14    New England          -10.666667
15          Miami          -10.000000
16      N.Y. Jets          -28.000000
17      Baltimore           -2.857143
18     Washington          -11.142857
19   Jacksonville           -2.714286
20        Arizona           -5.857143
21    Kansas City           -1.142857
22      Las Vegas           11.833333
23    LA Chargers           12.714286
24      Minnesota           30.500000
25      Green Bay           13.285714
26    N.Y. Giants            5.857143
27      Tennessee           -9.833333
28      Tampa Bay            3.142857
29         Dallas           -4.285714
30        Seattle          -16.714286
31         Denver           -6.571429
32         Totals                 NaN